package com.atossyntel.springboot.service;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Scanner;

public class EncrypterHelper {
	// This simple tool should be run as a normal Java application
	// It will prompt the user for a password and return a hashed password to insert directly into the database by a database administrator
	// The structure of the returned password is [16-byte salt generated by Encrypter][hashed password returned by Encrypter]
	//   converted from a byte array to a URL-Encoded String (see Encrypter.matchPassword for how this is decoded back to a byte array)
	
	// Don't forget to make sure your local copy of the database has enough space to hold the larger new hashed passwords
	// ALTER TABLE employees MODIFY(password VARCHAR2(200));
	
	public static void main(String[] args) {
		Scanner in = new Scanner(System.in);
		System.out.print("Input password: ");
		String password = in.nextLine();
		in.close();
		System.out.println();
		System.out.println("Old password: [" + password + "]");
		try {
			System.out.println("New password: [" + Encrypter.encryptPassword(password.toCharArray()) + "]");
		} catch (NoSuchAlgorithmException e) {
			System.out.println("error");
		} catch (InvalidKeySpecException e) {
			System.out.println("error");
		}
	}
}